import { useAuth0 } from "@auth0/auth0-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

/**
 * CallbackPage supports two callback conditions:
 *
 * 1) Auth0 callback: /callback?code=...&state=... (handled by Auth0 SDK).
 * 2) B2C callback: /callback?code=...&state=... where state matches the
 *    value generated by ConnectInsightsAI before redirecting to B2C.
 *
 * For B2C, this page sends the auth code to the Python backend, which performs
 * token exchange using client_secret (server-side only).
 */
const CallbackPage = () => {
  const { isLoading, isAuthenticated, error } = useAuth0();
  const navigate = useNavigate();
  const [b2cExchangeState, setB2cExchangeState] = useState({
    status: "idle",
    message: "",
    data: null,
  });

  const extractParams = () => {
    const params = new URLSearchParams(window.location.search);
    const hash = window.location.hash.startsWith("#")
      ? window.location.hash.slice(1)
      : window.location.hash;
    const hashParams = new URLSearchParams(hash);

    return {
      idToken: params.get("id_token") || hashParams.get("id_token"),
      accessToken: params.get("access_token") || hashParams.get("access_token"),
      state: params.get("state") || hashParams.get("state"),
      code: params.get("code") || hashParams.get("code"),
      error: params.get("error") || hashParams.get("error"),
      errorDescription:
        params.get("error_description") || hashParams.get("error_description"),
    };
  };

  const decodeJwt = (token) => {
    try {
      const parts = token.split(".");
      if (parts.length !== 3) {
        return null;
      }

      const decodePart = (value) => {
        const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
        const padded =
          normalized + "=".repeat((4 - (normalized.length % 4)) % 4);
        return JSON.parse(window.atob(padded));
      };

      return {
        header: decodePart(parts[0]),
        payload: decodePart(parts[1]),
        signature: parts[2],
      };
    } catch {
      return null;
    }
  };

  const callbackData = useMemo(() => {
    const params = extractParams();
    console.log("params", params);
    const expectedState = sessionStorage.getItem("b2c_oauth_state");
    const storedRedirectUri = sessionStorage.getItem("b2c_oauth_redirect_uri");
    const fallbackToken = localStorage.getItem("insights_ai_token");
    const token = params.idToken || fallbackToken;

    const isB2cCodeCallback =
      Boolean(params.code) &&
      Boolean(expectedState) &&
      params.state === expectedState;
    console.log("isB2cCodeCallback", isB2cCodeCallback);
    const isAuth0CodeCallback = Boolean(params.code) && !isB2cCodeCallback;

    if (!token) {
      return {
        source: null,
        token: null,
        decoded: null,
        params,
        expectedState,
        storedRedirectUri,
        isB2cCodeCallback,
        isAuth0CodeCallback,
      };
    }

    return {
      source: params.idToken ? "url" : "localStorage",
      token,
      decoded: decodeJwt(token),
      params,
      expectedState,
      storedRedirectUri,
      isB2cCodeCallback,
      isAuth0CodeCallback,
    };
  }, []);
  console.log("callbackData", callbackData);
  useEffect(() => {
    if (!callbackData.isB2cCodeCallback || b2cExchangeState.status !== "idle") {
      return;
    }

    const exchangeCode = async () => {
      setB2cExchangeState({ status: "loading", message: "", data: null });

      try {
        const verifier = sessionStorage.getItem("code_verifier");
        console.log("verifier", verifier);
        console.log("soifhaohfa", {
          code: callbackData.params.code,
          code_verifier: verifier,
          redirect_uri:
            callbackData.storedRedirectUri ||
            `${window.location.origin}/callback`,
        });
        const response = await fetch("/api/b2c/token-exchange", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            code: callbackData.params.code,
            code_verifier: verifier,
            redirect_uri:
              callbackData.storedRedirectUri ||
              `${window.location.origin}/callback`,
          }),
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(
            data?.error_description || data?.error || "Token exchange failed.",
          );
        }

        localStorage.setItem("insights_ai_connected", "true");

        // Store only the session_id in sessionStorage — raw tokens stay on the backend
        if (data.session_id) {
          sessionStorage.setItem("b2c_session_id", data.session_id);
        }

        sessionStorage.removeItem("b2c_oauth_state");
        sessionStorage.removeItem("b2c_oauth_redirect_uri");

        setB2cExchangeState({ status: "success", message: "", data });
      } catch (exchangeError) {
        setB2cExchangeState({
          status: "error",
          message: exchangeError.message,
          data: null,
        });
      }
    };

    exchangeCode();
  }, [b2cExchangeState.status, callbackData]);

  // If the B2C code callback is active, skip the Auth0 SDK error entirely —
  // Auth0 throws "Invalid state" because the state belongs to B2C, not Auth0.
  if (error && !callbackData.isB2cCodeCallback) {
    return (
      <div className="page fade-in">
        <div className="error-banner">
          <h2>Authentication Error</h2>
          <p>{error.message}</p>
        </div>
      </div>
    );
  }

  if (callbackData.params.error) {
    return (
      <div className="page fade-in">
        <div className="error-banner">
          <h2>Callback Error</h2>
          <p>
            {callbackData.params.errorDescription || callbackData.params.error}
          </p>
        </div>
      </div>
    );
  }

  if (callbackData.isB2cCodeCallback && b2cExchangeState.status === "loading") {
    return (
      <div className="page fade-in">
        <div className="spinner-wrapper">
          <div className="spinner" />
          <p>Exchanging authorization code via backend...</p>
        </div>
      </div>
    );
  }

  if (callbackData.isB2cCodeCallback && b2cExchangeState.status === "error") {
    return (
      <div className="page fade-in">
        <div className="error-banner">
          <h2>B2C Token Exchange Failed</h2>
          <p>{b2cExchangeState.message}</p>
          <button
            className="btn btn-primary"
            onClick={() => navigate("/dashboard")}
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  if (callbackData.isB2cCodeCallback && b2cExchangeState.status === "success") {
    return (
      <div className="page fade-in">
        <div className="b2c-callback-container">
          <div className="callback-header">
            <h1>Insights AI Connected</h1>
            <p className="callback-subtitle">
              Authorization code exchanged successfully by backend.
            </p>
          </div>

          <div className="token-section">
            <h2>Session Established</h2>
            <p>
              Your B2C session is active. Tokens are managed securely on the
              backend — your browser holds only a session reference.
            </p>
          </div>

          <div className="callback-actions">
            <button
              className="btn btn-primary"
              onClick={() => navigate("/dashboard")}
            >
              Back to Dashboard
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (callbackData.isAuth0CodeCallback) {
    return (
      <div className="page fade-in">
        <div className="spinner-wrapper">
          <div className="spinner" />
          <p>Completing Auth0 sign-in...</p>
        </div>
      </div>
    );
  }

  if (isLoading && !callbackData.token) {
    return (
      <div className="page fade-in">
        <div className="spinner-wrapper">
          <div className="spinner" />
          <p>Completing sign-in...</p>
        </div>
      </div>
    );
  }

  if (!callbackData.token) {
    return (
      <div className="page fade-in">
        <div className="error-banner">
          <h2>No Callback Token Found</h2>
          <p>No B2C token was found for this callback request.</p>
          <button
            className="btn btn-primary"
            onClick={() => navigate("/dashboard")}
          >
            Go to Dashboard
          </button>
        </div>
      </div>
    );
  }

  if (!callbackData.decoded) {
    return (
      <div className="page fade-in">
        <div className="error-banner">
          <h2>Invalid JWT</h2>
          <p>Token exists but could not be decoded as a valid JWT.</p>
        </div>
      </div>
    );
  }

  const { header, payload } = callbackData.decoded;

  return (
    <div className="page fade-in">
      <div className="b2c-callback-container">
        <div className="callback-header">
          <h1>B2C JWT Decoder</h1>
          <p className="callback-subtitle">
            Token source: <strong>{callbackData.source}</strong>
            {isAuthenticated ? " | Auth0 session is active" : ""}
          </p>
        </div>

        <div className="token-section">
          <h2>JWT Header</h2>
          <pre className="json-block">{JSON.stringify(header, null, 2)}</pre>
        </div>

        <div className="token-section">
          <h2>JWT Payload</h2>
          <pre className="json-block">{JSON.stringify(payload, null, 2)}</pre>
        </div>

        <div className="token-section">
          <h2>Callback Params</h2>
          <pre className="json-block">
            {JSON.stringify(callbackData.params, null, 2)}
          </pre>
        </div>

        <div className="callback-actions">
          <button
            className="btn btn-primary"
            onClick={() => navigate("/dashboard")}
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    </div>
  );
};

export default CallbackPage;
